drone_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from drone_inventory.forms import UserLoginForm
from drone_inventory.models import User, db
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, login_required



auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST']) #always going to be a list and always be methods
def signup():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            first_name = form.first_name.data
            last_name = form.last_name.data
            password = form.password.data

            user = User(email, first_name, last_name, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f"You have succesfully created a User account {email}", "user-created")

            return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')

    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were succesfully logged in via Email/Password', 'auth-success')
                return redirect(url_for('site.profile'))

            else:
                flash("Your email/password is invalid.", 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception("Invalid Form Data: Please Try Again, dawg")


    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

drone_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site', __name__, template_folder='site_templates')

"""
Note that in the above code,
some arguments are specified when creating a clueprint object.
The first argument, "site", is the Blueprint name as a string,
which is used my flask's routing mechanism. 
The second argument __name__ is the Blueprint's import name,
which Flask uses to locate the Blueprint's resources.
The third is telling Flask where to find the html to render.
"""

@site.route('/')
def home():
    return render_template('index.html')


@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

drone_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Title</title>
</head>
<body>
    <nav class="ct-nav">
        <div>
            <img src="../static/images/Coding Drones Logo.png" alt="Coding Drones Logo">
        </div>

        <!-- Nav Items -->
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Coding Drones Project</li>
                </a>
                <a href="{{ url_for('site.home') }}">                    
                    <li>Home</li>
                </a>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                 <a href="{{ url_for('auth.logout') }}">
                    <li>Logout</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up</li>
                </a>
                {% endif %}


                <!-- TODO: Add navigation for sign up and sign in -->
            </ul>

        </div>   
    </nav>

    <!-- End of Nav -->

    {% block content %}

    {% endblock content %}




<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

drone_inventory/templates/forms.html
<!-- HTML Produced By the Flask Form -->

<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here!")}}
        </fieldset>

        <fieldset id="first-field">
            {{ form.first_name.label }}
            {{ form.first_name(class = "form-control", placeholder = "First Name") }}

        </fieldset>
        <fieldset id="last-field">
            {{ form.last_name.label }}
            {{ form.last_name(class = "form-control", placeholder = "Last Name") }}

        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder = "Place Password Here!") }}
        </fieldset>

        <!-- Submit Button Area -->
        {{ form.submit_button(class = 'btn btn-primary btn-block') }}


    </div>
</form>